# Generated by Django 3.1.7 on 2021-03-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('idaddress', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('streetaddress', models.CharField(db_column='streetAddress', max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
                ('state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deliverydriver',
            fields=[
                ('driverid', models.AutoField(db_column='driverID', primary_key=True, serialize=False)),
                ('driverfirstname', models.CharField(db_column='driverFirstName', max_length=45)),
                ('driverlastname', models.CharField(db_column='driverLastName', max_length=45)),
                ('carmodel', models.CharField(db_column='carModel', max_length=45)),
                ('licenseplate', models.CharField(db_column='licensePlate', max_length=45)),
            ],
            options={
                'db_table': 'deliveryDriver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groceryitem',
            fields=[
                ('groceryid', models.AutoField(db_column='groceryID', primary_key=True, serialize=False)),
                ('groceryname', models.CharField(db_column='groceryName', max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('stock', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'groceryItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grocerystore',
            fields=[
                ('idgrocerystore', models.AutoField(db_column='idgroceryStore', primary_key=True, serialize=False)),
                ('storename', models.CharField(db_column='storeName', max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'groceryStore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grocerystoreadd',
            fields=[
                ('groceryaddressid', models.AutoField(db_column='groceryAddressID', primary_key=True, serialize=False)),
                ('streetaddress', models.CharField(db_column='streetAddress', max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
                ('state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'groceryStoreAdd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('idorderstatus', models.AutoField(db_column='idorderStatus', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'orderStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseinfo',
            fields=[
                ('idpurchaseinfo', models.AutoField(db_column='idpurchaseInfo', primary_key=True, serialize=False)),
                ('totalprice', models.CharField(db_column='totalPrice', max_length=45)),
                ('totalitems', models.CharField(db_column='totalItems', max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('time', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'purchaseInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('emailaddress', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userpaymentinfo',
            fields=[
                ('paymentid', models.AutoField(db_column='paymentID', primary_key=True, serialize=False)),
                ('cardnumber', models.CharField(max_length=16)),
                ('securitynumber', models.IntegerField()),
                ('expirationdate', models.CharField(db_column='expirationDate', max_length=10)),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'userPaymentInfo',
                'managed': False,
            },
        ),
    ]
