# Generated by Django 3.1.7 on 2021-04-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210323_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseinfoHasGroceryitem',
            fields=[
                ('purchaseinfo_purchaseid', models.OneToOneField(db_column='purchaseInfo_purchaseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hello.purchaseinfo')),
            ],
            options={
                'db_table': 'purchaseInfo_has_groceryItem',
                'managed': False,
            },
        ),
    ]
